name: Build
run-name: Build
on:
  push:
  pull_request:

jobs:
  compile-glfw:
    name: Build ${{ matrix.os }} glfw
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: mlugg/setup-zig@v2.0.5
        with:
          version: 0.15.2
      - name: Build with GLFW
        shell: bash
        run: |
          set -euo pipefail
          zig build -Dglfw
          zig build --build-file ./examples/3d/build.zig -Dglfw
          ls ./zig-out/bin
          
  build-windows-native:
    runs-on: windows-latest
    name: Build windows native
    steps:
      - uses: actions/checkout@v6
      - uses: mlugg/setup-zig@v2.0.5
        with:
          version: 0.15.2
      - name: Build
        shell: bash
        run: |
          set -euo pipefail
          zig build
          zig build --build-file ./examples/3d/build.zig
          ls ./zig-out/bin
          

