name: compile
run-name: ${{ github.actor }} compile linux
on:
  push:
  pull_request:
jobs:
  compile-linux-glfw:
    runs-on: ubuntu-latest
    name: Build linux glfw
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2
      - name: Build with GLFW
        run: |
          zig version && zig build -Dglfw
